Fix compiler warning for unused variable
'''
amec/amec_sensors_power.c:285:14: error: variable ‘avddPower’ set but not used [-Werror=unused-but-set-variable]
'''

Change-Id: If88acd396be611dfbd82a0616b3ca9a58b2c96d8
Reviewed-on: http://rchgit01.rchland.ibm.com/gerrit1/c/occ/+/189332
Reviewed-by: Chris Cain <cjcain@us.ibm.com>
Tested-by: FSP CI Jenkins <fsp-CI-jenkins+hostboot@us.ibm.com>